# docker-compose.yml
version: '3'
services:
  image_service:
    build: ./image-service
    ports:
      - "5000:5000"
    volumes:
      - ./output:/app/output  # Make sure this is correctly set
  
  ui_service:
    build: ./ui-service
    ports:
      - "5005:5005"
    depends_on:
      - image_service

volumes:
  db_data: