# docker-compose.yml
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Porta para os clientes se conectarem
      - "15672:15672"  # Porta da interface de administração
    networks:
      - rabbitmq_network

  ui_service:
    build: ./ui-service
    ports:
      - "5005:5005"
    networks:
      - rabbitmq_network

  image_service:
    build: ./image-service
    ports:
      - "5000:5000"
    volumes:
      - ./output:/app/output  # Make sure this is correctly set
    networks:
      - rabbitmq_network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"  # Porta para acessar a interface do Prometheus
    networks:
      - rabbitmq_network  # Conecta o Prometheus à mesma rede dos outros serviços

networks:
  rabbitmq_network:
    driver: bridge

volumes:
  db_data: