# docker-compose.yml
version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Porta para os clientes se conectarem
      - "15672:15672"  # Porta da interface de administração
    networks:
      - rabbitmq_network

  ui_service:
    build: ./ui-service
    ports:
      - "5005:5005"
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    driver: bridge

volumes:
  db_data: